#!/bin/bash -euw

DEFAULT="\e[39m"
RESET="\e[0m"
RED="\e[31m"
BLUE="\e[34m"
LIGHT_BLUE="\e[94m"

PWD=`pwd`

FILES=( "bashrc" "nanorc" "gitignore_global" )

for FILE in "${FILES[@]}"; do
    if [ -f ~/.$FILE ]; then
        if [ "$(readlink ~/.$FILE)" != "$PWD/$FILE" ]; then
            echo -en $RED
            echo -e "\e[1m~/.$FILE\e[21m exists, but it's not our file. Move, then linking."
            mv ~/.$FILE ~/.$FILE.`date +%F`
            ln -s $PWD/$FILE ~/.$FILE
        else
            echo -en $LIGHT_BLUE
            echo -e "~/\e[1m.$FILE\e[21m exists, and it's our file."
        fi
    else
        echo -en $LIGHT_BLUE
        echo -e "\e[1m~/.$FILE\e[21m doesn't exists. Linking."
        ln -s $PWD/$FILE ~/.$FILE
    fi
done

echo -en $RESET

git config --global core.excludesfile ~/.gitignore_global

exec bash
